setup redux, login, registartion
AlexMoskalyk/cryptohub pull request #6
Opened 2024-11-25 14:33 UTC by AlexMoskalyk

2024-11-25 14:43 UTC, YuriiSkyba1 requested changes

2024-11-25 14:43 UTC, YuriiSkyba1 commented on src/redux/auth/authOperations.ts
> +    } catch (error:any) {
шось по типу

catch (error) {
      const firebaseError = error as FirebaseError;
      return thunkAPI.rejectWithValue({ errorMessage: firebaseError.message });
    }

2024-11-25 14:43 UTC, YuriiSkyba1 commented on src/redux/auth/authOperations.ts
> +    } catch (error:any) {
потрібно уникати any

2024-11-25 14:43 UTC, YuriiSkyba1 commented on src/redux/auth/authOperations.ts
> +    } catch (error:any) {
чи пробував ти типи який надає файр бейз щоб не писати any ?
import { FirebaseError } from 'firebase/app';

2024-11-25 14:43 UTC, YuriiSkyba1 commented on src/redux/auth/authOperations.ts
> +export const signUp = createAsyncThunk(
```
interface RejectValue {
  errorMessage: string;
}
interface AuthUser {
  uid: string;
  email: string | null;
}


export const signUp = createAsyncThunk<AuthUser, SignInCredentials, { rejectValue: RejectValue }>(
  'auth/signUp',
  async ({ email, password }: SignInCredentials, thunkAPI) => {
    try {
      const userCredential: UserCredential = await createUserWithEmailAndPassword(auth, email, password);
      const user = userCredential.user;
      return {
        uid: user.uid,
        email: user.email,
      };
    } catch (error) {
      const firebaseError = error as FirebaseError;
      return thunkAPI.rejectWithValue({ errorMessage: firebaseError.message });
    }
  }
);




```

2024-11-25 14:43 UTC, YuriiSkyba1 commented on src/redux/auth/authOperations.ts
> +export const signUp = createAsyncThunk(
стараємося типізовувати і створювати інтерфейси

2024-11-26 19:11 UTC, AlexMoskalyk commented on src/redux/auth/authOperations.ts
> +    } catch (error:any) {
додав новий коміт

2024-11-26 19:12 UTC, AlexMoskalyk commented on src/redux/auth/authOperations.ts
> +export const signUp = createAsyncThunk(
додав новий коміт

2024-11-27 08:58 UTC, YuriiSkyba1 approved these changes
зараз набагато краще
great job

2024-11-27 12:24 UTC, merged